### ISSUE TITLE
Router problems

### ISSUE THREAD

**Issue by cescoferraro** [NathanWalker/nativescript-ng2-magic#9]
I managed to get this library working with a  abrand new cli project on the nativescript side, but ng serve is still throwing me errors.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular/router-deprecated
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
        at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
        at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
    Error loading http://localhost:4200/vendor/@angular/router-deprecated as "@angular/router-deprecated" from http://localhost:4200/vendor/nativescript-ng2-magic/src/client/plugin/services/magic.service.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular/router-deprecated(…)consoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular/router-deprecated(…)consoleError @ zone.js:463
```

**Comment by NathanWalker** [comment]
You will need to ensure you have `router-deprecated` installed as it does not come preinstalled with angular cli setup...sample `package.json`:

```
"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
   ...
```

then will need to modify `src/system-config.ts` and add `'@angular/router-deprecated'`

Also ensure you are using the right directives from magic as mentioned here: https://github.com/NathanWalker/nativescript-ng2-magic#what-if-using-the-router for the deprecated router.

**Comment by cescoferraro** [comment]
The thing is I am not using the router at all. I rather use the new router while we wait for the new new router. Does that change anything or I still need to install the deprecated one? @NathanWalker

**Comment by NathanWalker** [comment]
Still need to install the deprecated one just to suffice the compiler. 👍
